version: '2.1'

services:  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}-legacy
    ports:
      - "8480:8080"
    volumes:
      - ./keycloak/kogito-realm.json:/tmp/kogito-realm.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/realms/kogito" ]
      interval: 1s
      timeout: 1s
      retries: 50
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: ${DOCKER_GATEWAY_HOST:-host.docker.internal}:5432
      DB_DATABASE: keycloak
      DB_USER: smx
      DB_SCHEMA: public
      DB_PASSWORD: smx
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/kogito-realm.json

  data-index:
    container_name: data-index
    image: quay.io/kiegroup/kogito-data-index-postgresql:1.30
    networks:
      - smx_default
    ports:
      - "8180:8080"
    volumes:
      - ./target/protobuf:/home/kogito/data/protobufs/
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5432/data_index"
      QUARKUS_DATASOURCE_USERNAME: smx
      QUARKUS_DATASOURCE_PASSWORD: smx
      KAFKA_BOOTSTRAP_SERVERS: smx_kafka_1:9092
      KOGITO_DATA_INDEX_PROPS: -Dquarkus.hibernate-orm.database.generation=update

  management-console:
    container_name: management-console
    image: quay.io/kiegroup/kogito-management-console:1.30
    ports:
      - "8280:8080"
    depends_on:
      data-index:
        condition: service_started
      keycloak:
        condition: service_healthy
    volumes:
      - ../target/classes/META-INF/processSVG/:/home/kogito/data/svg/
    environment:
      KOGITO_DATAINDEX_HTTP_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8180/graphql
      KOGITO_MANAGEMENT_CONSOLE_PROPS: -Dkogito.consoles.keycloak.config.url=http://localhost:8480/auth
        -Dkogito.consoles.keycloak.config.health-check-url=http://localhost:8480/auth/realms/kogito/.well-known/openid-configuration
        -Dkogito.svg.folder.path=/home/kogito/data/svg

  task-console:
    container_name: task-console
    image: quay.io/kiegroup/kogito-task-console:1.30
    ports:
      - "8380:8080"
    depends_on:
      data-index:
        condition: service_started
      keycloak:
        condition: service_healthy
    environment:
      KOGITO_DATAINDEX_HTTP_URL: http://${DOCKER_GATEWAY_HOST:-host.docker.internal}:8180/graphql
      KOGITO_TASK_CONSOLE_PROPS: -Dkogito.consoles.keycloak.config.url=http://localhost:8480/auth
        -Dkogito.consoles.keycloak.config.health-check-url=http://localhost:8480/auth/realms/kogito/.well-known/openid-configuration
networks:
  smx_default:
    external: true